In [19]:
import numpy as np
from numpy import newaxis

a = np.arange(10, 40, 5).reshape(3, 2)

for element in a.flat:
    element # do something
    
type(a) # numpy.ndarray

a.T # TRANSPOSE of a ***
a.ravel() # out: array([10, 15, 20, 25, 30, 35]), returns array flattened

a.resize(2, 3) # MODIFIES array, reshapes

b = np.array([4.,2.])
b.dtype # float64

b[:, newaxis] # returns a 2D columns vector

# np.hsplit() -> split along horizontal axis  boyunca
# np.split() -> split along vertical axis, y eksenini kesicek şekilde düşün

np.hsplit(a, 3)
np.vsplit(a, 2)[0] # [[10 15 20]]

c = a    # no new object is created
c is a   # True, a and c are two names for the same ndarray object

# Python passes mutable objects as references, so function calls make no copy

d = a.view()
# different array objects can share the same data
d is a # false
d[0, 1] = 3    # a's data changes


e = a.copy()    # deep copy of a
print(e)
e[0, 1] = 7000 # a's data does not change

# in order to copy or view
# ------------------------
# array.view(), array.copy()

x = np.array([5])
y = np.array([[5]])
x.shape # (1,)
y.shape # (1, 1)
x.itemsize # 4

i = np.array([0, 1]) # an indices array
j = np.array([1, 2])
a[i, j]    # array([ 3, 35])

a.sum() # add all of the elements in the array, 123
a.mean() # 20.5

a.max(axis = 1) # array([20, 35])

f = np.random.random(3) #[0.77190879 0.16670991 0.97683164]
f.dtype # float64

g = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
np.unique(g) # array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

[[10  3 20]
 [25 30 35]]


array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])