In [20]:
import numpy as np

a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

# indices of unique elements
indices_list = np.unique(a, return_index=True)

a_2d = np.array([[1, 2, 3, 4], 
                 [5, 6, 7, 8], 
                 [9, 10, 11, 12]])

# with axis we specified what we want
unique_rows = np.unique(a_2d, axis=0)

b = np.linspace(0, 10, 5)

# REVERSE ARRAY -> np.flip()
reversed_array = np.flip(b)

# reverse the content in all of the rows and all of the columns
reversed_2d_arr = np.flip(a_2d)
reversed_2d_arr
# [[12 11 10  9]
#  [ 8  7  6  5]
#  [ 4  3  2  1]]

# reverse only rows
revrs_row_arr = np.flip(a_2d, axis = 0)
# reverse only columns
revrs_col_arr = np.flip(a_2d, axis = 1)

# reverse the contents of only one column or row
# for example, reverse row at index poisiton 1, (2nd row)
a_2d[1] = np.flip(a_2d[1])

# reverse column at index 1, 2nd column
a_2d[:,1] = np.flip(a_2d[:,1])

a.flatten() # flatten array into 1D array

# when you use ravel, the changes you make to the new array will affect the parent array
a_new = a_2d.ravel()

# changes to a_new will affect a_2d

''' Every object contains the reference to a string, which is known as the docstring. 
In most cases, this docstring contains a quick and concise summary of the object and how to use it. 
Python has a built-in help() function that can help you access this information'''

help(max)

Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value
    
    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the largest argument.

